elasticsearch:
  image: elasticsearch:7.14.1
  ports:
  - 9200:9200
  environment:
  - discovery.type=single-node
logstash:
  image: logstash:7.14.1
  links:
  - elasticsearch:elasticsearch
  ports:
  - 5044:5044
kibana:
  image: kibana:7.14.1
  links:
  - elasticsearch:elasticsearch
  ports:
  - 5601:5601
  environment:
  - ELASTICSEARCH_URL=http://elasticsearch:9200
