---

- name: Deploying ELK Stack
  hosts: appsrvgrp
  become: yes

  tasks:
  - name: Copying docker-compose file
    copy: src=elk1/docker-compose.yml dest=~/home/ubuntu/

  - name: Running docker-compose.yml
    command: sudo docker-compose -f ~/home/ubuntu/docker-compose.yml up -d
      
  - name: Removing docker compose file
    command: sudo rm -f ~/home/ubuntu/docker-compose.yml 
